import Head from "next/head";
import Layout from "../features/layout/Layout";
import Home from "../features/home";
const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Nabtana | ናብታና</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </div>
  );
};

export default HomePage;
